version: "3.9"
services:
  base_no_env: &base_no_env
    image: "robdmc/dockerjupyterpostgres"
    links:
      - db
    volumes:
      - ./dbdump:/dbdump
      - ./code:/code
      - penv:/env

  base: &base
    <<: *base_no_env
    env_file: variables.env

  shell:
    <<: *base
    command: /bin/bash

  test:
    <<: *base_no_env
    working_dir: /code
    command: /bin/bash

  build_env:
    <<: *base_no_env
    entrypoint: /code/build_env.sh

  make_test_db:
    <<: *base
    entrypoint: /code/make_test_db.sh

  load_db:
    <<: *base
    entrypoint: /code/load_db_table.sh


  truncate:
    <<: *base
    entrypoint: /code/truncate.py 

  notebook:
    <<: *base
    ports:
        - "9999:9999"
    working_dir: /code
    command: jupyter-lab  --port=9999  --NotebookApp.iopub_data_rate_limit=10000000000 --allow-root --no-browser --ip=0.0.0.0

  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - db-data:/var/lib/postgresql/data        

volumes:
  db-data:
    driver: local
  penv:
    driver: local
